### ISSUE TITLE
Error using in Flutter add to app module on iOS

### ISSUE THREAD

**Issue by soyangel** [PhilipsHue/flutter_reactive_ble#104]
**Describe the bug**
Cannot use this library on a Flutter "add to app" module on iOS. There are errors on the pod install step when building the frameworks.

**To Reproduce**
- Create flutter module for add to app: 
```
flutter create --template module my_flutter
```
- On this module add flutter_reactive_ble as a dependency
- Building frameworks fails: 
```
flutter build ios-framework --output=frameworks
```

There is an error about the iOS version that can be fixed editing the module´s .ios/Podfile and setting:

```    
platform :ios, '10.0'
```

Also there is an error about Swift version not defined that can be fixed adding this line on fluttter_reactive_ble/ios/flutter_reactive_ble.podspec:

```
s.swift_version       = '4.0'
```

**Expected behavior**

**Smartphone / tablet**

**Peripheral device**

**Additional context**

**Comment by werediver** [comment]
Hi, @soyangel. Thanks for providing useful info.

I specified the Swift version (4.2) in the library's podspec in #107. The deployment target is a property of your module, so that you still need to specify yourself. Every library provides its own deployment target as a _constraint_ to the top-level deployment target that you have to choose for you module (or an app). This library requires iOS 10.0 or newer.
