### ISSUE TITLE
Question: is connectToAdvertisingDevice() method android only?

### ISSUE THREAD

**Issue by iJamesPHP** [PhilipsHue/flutter_reactive_ble#135]
Is the connectToAdvertisingDevice() method android only? It hangs for me and never connects on iOS. Does it require you to stop scanning before using it?

**Comment by werediver** [comment]
`connectToAdvertisingDevice(⋯)` wasn't designed as Android specific. It should work on iOS, but you don't need it there, because iOS is very good at establishing connections (and handling BLE in general). I'd recommend to check if the program is running on Android before using this method.

If I remember correctly, the scanning should be stopped before you invoke it (regardless of the platform), indeed. @remonh87 could you comment on this?

**Comment by remonh87** [comment]
yes it is advised to stop scanning before invoking it else especially on Android it can lead to flaky results.
