### ISSUE TITLE
How to print the response from writeCharacteristicWithResponse?

### ISSUE THREAD

**Issue by 0100101101001011** [PhilipsHue/flutter_reactive_ble#150]
**Describe the question**
I am trying to print the response from a **writeCharacteristicWithResponse** in my flutter app. But it says: _**This expression has a type of 'void' so its value can't be used.**_  I am not sure how to handle it.

**To Reproduce**
![image](https://user-images.githubusercontent.com/13026382/99868685-974d1c00-2bff-11eb-90a7-bcb3934a9abd.png)

**Comment by werediver** [comment]
The "response" in "write characteristic with response" means "an acknowledgement of reception". The write can either be acknowledged (success) or failed (an exception is thrown), thus the return type is `void` and there is nothing to print (though you can `print("Write successful")` and in a catch-clause `print("Write failed: $e")`).

BLE does not provide a request-response mechanism like you may know from HTTP out of the box. If you need to perform request-response calls, you will need to implement a custom mechanism on top of the basic BLE functionality. A typical approach is to implement a "control point": a characteristic that is writable and delivers [notifications or indications](https://duckduckgo.com/?q=BLE+"indications"+vs+"notifications"), so that a request is written to it and a response is delivered back as a notification or an indication.
