### ISSUE TITLE
BT devices visibility

### ISSUE THREAD

**Issue by dawidb-appdate** [PhilipsHue/flutter_reactive_ble#192]
**Describe the bug**
It seems that once bt devices is discovered it's not been removed from found devices (example app) when disconnected from power source. Is it possible to achieve that with FlutterReactiveBle's scanForDevices method?

**To Reproduce**
1. launch example app 
2. hit Scan button
3. wait until your bt device is visible
4. power down your bt device (it's still on the list)

**Expected behavior**
BleScannerState should remove devices from discoveredDevices when device is not powered or is not within range.

**Comment by remonh87** [comment]
@dawidb-appdate  our library only propagate the devices found through ble discovery. In our example app we just have list with all devices found during the discovery but it is difficult to facilitate your use case due to how ble discovery works, [technical explanation](https://microchipdeveloper.com/wireless:ble-link-layer-discovery). 

For example we have. 3 BT devices (device1 device2, device3) that we keep powered on during ble discovery. When scanning the following updates can be emitted:
- device1 device2 device3
- device2 device3
- device1, device3
- device1 device2 device3

If you want to implement this usecase  you need to have your own registry where you keep track of when the devices are found and omit the devices that are not found anymore after 5 seconds.

**Comment by dawidb-appdate** [comment]
thank you
