### ISSUE TITLE
Readme does not make apparent the pre-requisites for using characteristics.

### ISSUE THREAD

**Issue by safield** [PhilipsHue/flutter_reactive_ble#206]
I am a first time user reading the readme of this library.

Specifically I am looking at the examples provided for reading, writing, and subscribing to a characteristic.

I assume I must be connected to a device to deal with characteristics, but the readme does not inform if this is the case. In addition, the library by design allows one to deal with characteristics without first being connected. If a ConnectionStateUpdate provided a conditionally present object that represented a handle to a device, which was required to subscribe to characteristics, there would be no confusion about whether a connected device was needed.

**Comment by remonh87** [comment]
@safield  I agree with you that adding examples to our app regarding read and write is what we are missing so that is something to work on.

However I think that our in code documentation is quite self-explaining, if not please let us know so we can improve there as well.  If you would try to read a characteristic without the device being connected our library would thrown an exception informing you that you need to be connected.
