### ISSUE TITLE
Difference with flutter_blue

### ISSUE THREAD

**Issue by boskokg** [PhilipsHue/flutter_reactive_ble#22]
Hello,

We are using the flutter_blue plugin.

Does anyone know how is this plugin better?

**Comment by remonh87** [comment]
I can only explain our motivation for writing the plugin instead of using Flutterblue.

I think for basic usecases FlutterBlue works but we missed the following at the time we started:

- Support maintaining connections with multiple devices at the same time.
- Has facilities to work around Android issues (prescan and connect, request connection priority, clear gatt cache)
- Clear Reactive API
