### ISSUE TITLE
Why not expose a method for overriding RxJavaPlugins.setErrorHandler on Dart side?

### ISSUE THREAD

**Issue by splangi** [PhilipsHue/flutter_reactive_ble#262]
**Is your feature request related to a problem? (please describe)**
com.polidea.rxandroidble2.exceptions.BleException crashes the Android application

**Describe the solution you'd like**
A Stream returning method on dart side that would override the RxJavaPlugins.setErrorHandler in Android side. That way the user can override the method in dart code only without writing any native code. Those users who are using RxJavaPlugin natively just avoid calling it (which is probably a minority). Also this stream would pass the BleExceptions on the dart side for handling.

**Describe alternatives you've considered**
If this is too complex, then a simple overriding method could be exposed on dart side that would override the error handler on Android side and print those BleExceptions. 

**Additional context**
This would be no op on iOS side.

**Comment by remonh87** [comment]
Can you explain me which exception you get? Is it the `UndeliverableException` or is it something else? The `UndeliverableException`  is the only exception we do not handle see also FAQ. If the app crashes because of sth else I consider this as a bug and would be great if you can provide me some logs in that case.
