### ISSUE TITLE
Maintaining connection status of multiple BLE devices

### ISSUE THREAD

**Issue by Santhosh12Rsk** [PhilipsHue/flutter_reactive_ble#274]
If i connect the new device already connected device is disconnected unable to connect multiple devices.

**Comment by werediver** [comment]
Almost certainly the problem is in your implementation around the library. The library is designed to handle arbitrary number of connections, though the limits imposed by iOS and Android are relatively low.

If you want to have a chance for a more detailed feedback, you need to provide much more details. First of all, do not ignore the issue template, and in this case provide the relevant code you wrote, as well.
