### ISSUE TITLE
writeCharacteristicWithoutResponse fail

### ISSUE THREAD

**Issue by spd-heshuip** [PhilipsHue/flutter_reactive_ble#28]
writeCharacteristicWithoutResponse fail;

**Comment by werediver** [comment]
@spd-heshuip Please care to provide enough input to enable us to help you resolve your issue.

Some points to check:

- make sure you use the correct service ID and characteristic ID that are actually present on the peripheral you're connected to
- BLE operations can fail, that's fine. Often a failure is followed by a connection loss, but there can be other reasons

**Comment by spd-heshuip** [comment]
@werediver Hi，I have check my code again .  the serviceId and characteristic id is correct .and i use light blue to test ,it is work . but use the library it is fail;
![image](https://user-images.githubusercontent.com/8907462/75234186-1807f480-57f5-11ea-91fb-1de7766dfb84.png)

**Comment by Taym95** [comment]
What do you mean by `fail`? can you give the whole error output with reproducing example? only `writeCharacteristicWithoutResponse fail;` doesn't really help.

**Comment by spd-heshuip** [comment]
here is my test code:
![image](https://user-images.githubusercontent.com/8907462/75234554-c4e27180-57f5-11ea-960d-25afbb5529a8.png)
![image](https://user-images.githubusercontent.com/8907462/75234582-cf047000-57f5-11ea-8f99-73341b74cd8e.png)
and here is the log:
![image](https://user-images.githubusercontent.com/8907462/75235201-d11afe80-57f6-11ea-89e4-499f4e7e1c22.png)

**Comment by spd-heshuip** [comment]
when i call the writeCharacteristicWithoutResponse function, it is block and did not return;

**Comment by werediver** [comment]
@spd-heshuip I suspect your code does not use `flutter_reactive_ble` API correctly, because that's a pretty basic use case and I am sure it works. We use `writeCharacteristicWithoutResponse(⋯)` for peripherals' firmware update, for instance, and have no issues with that.

Please check your code agains the example app. If you still need assistance in resolving your issue, you'd have to provide a complete piece of code or an example project to reproduce the issue.

I see you're connecting to another smartphone in a peripheral role. Is it your app on the other end? Are you sure _that_ one is works correctly?

Are you able to perform write without response via another application line nRF Connect?
