### ISSUE TITLE
Disconnect while connecting, can not connect to any device anymore

### ISSUE THREAD

**Issue by LiangHuangBC** [PhilipsHue/flutter_reactive_ble#301]
**Describe the bug**
Disconnect while connecting, can not connect to any device anymore

**To Reproduce**
1. Run Example app
2. Scan and found two devices. Connect to anyone works well.
3. Turn deviceA's power down. 
4. Connect to Device A, it shows connecting.
5. Return to scan list, connect to DeviceB, it shows connecting forever. 
6. Now you cannot connect to any device anymore.  Unless you restart app, or turn Device A on and connect to device A will be succeed, and everything works.

**Expected behavior**
After disconnecting from connecting device, it can connect to other device.

**Smartphone / tablet**
Run example app on Amazon Fire 8.

**Comment by LiangHuangBC** [comment]
tried deinitialize(), no luck

**Comment by benoit-rolandeau-act** [comment]
From my experience, the auto connection doesn't work well with some smartphones and may cause this problem. Do you use the auto connection?

**Comment by LiangHuangBC** [comment]
I turned auto to false, same issue.

**Comment by benoit-rolandeau-act** [comment]
Did you receive a "Disconnected" event when connecting to DeviceB (when you say that you wait forever)?

**Comment by remonh87** [comment]
@LiangHuangBC  do you use the `connectToDevice ` method  or the `connectToAdvertisingDevice ` ?  The last one is more safe since we will scan for the availability of the device before we connect to it. If you use the connectToDevice and the device is powered off you run into the issue that Android will attempt to connect forever . This is something in the OS and we cannot fix this. I suggest to use `connectToAdvertisingDevice` in that case.

**Comment by remonh87** [comment]
Closing for now feel free to reopen it in case you have additional questions

**Comment by LiangHuangBC** [comment]
Actually you can fix it. I passed it around. When disconnect, wait for connecting timeout. Then disconnecting works and all other connecting work.

**Comment by yuriboeira11tx** [comment]
How to set ```autoConnect``` to false?
