### ISSUE TITLE
Connect to Serial Port Protocol device

### ISSUE THREAD

**Issue by h0x00i** [PhilipsHue/flutter_reactive_ble#303]
Connect to Serial Port Protocol device [exp: HC-05, ESP32, NRF] for monitoring and control iot device development board.
this package have this feature [https://github.com/edufolly/flutter_bluetooth_serial](url), But it is no longer developed.

**Comment by werediver** [comment]
You want to work over RFCOMM protocol. Similar questions were asked before. Please, see

- #189, especially [this comment](https://github.com/PhilipsHue/flutter_reactive_ble/issues/189#issuecomment-759317176)
- #232 
- #191, the enabled

For now RFCOMM is not supported, because L2CAP APIs are not supported. Please, follow the updates in #191, but be aware that no one is actively working on it at the moment.
