### ISSUE TITLE
Missing unsubscribeCharacteristicUpdateNotification

### ISSUE THREAD

**Issue by zikambrani** [PhilipsHue/flutter_reactive_ble#341]
When i am already subscribe with notification in screen A and when I am leaving the screen,  calling .deinitialize() to unsubscribe and close connection which makes problem to resubscribe notification on chars...  (Write characteristic error occured..)
ROCHE - ACCU-CHEK INSTANT

**Comment by remonh87** [comment]
Can you be a bit more explicit about what the problem is? I think you shouldn't deinitialize the library but just maintain the subscription and use a proper state management solution (can be even value notifier). to propagate the value to the next screen.  Maintaining subscriptions inside the screen class is maybe not the best way to go. Check out our example app.
