### ISSUE TITLE
How to handle reconnects on device to far away or ble connection fails.

### ISSUE THREAD

**Issue by skast96** [PhilipsHue/flutter_reactive_ble#356]
Do you guys have a best practice example on how to handle auto reconnects on failures. Is the StreamSubscription var disposed after failure or trying to reconnect to the device itself? Do i have to call connectToAdvertisingDevice again and reinit the subscription?

Edit: After I disable bluetooth on my device (while being connected to the service device) and try to reconnect i always get a "Device is not advertising" error.

**Comment by remonh87** [comment]
true if you use `preScanAndConnect`  on Android we check if the device  is advertising in order to prevent the Android bleeding stack to wait for eternity to connect to the device.  What you can do for example is subscribe to: 
https://github.com/PhilipsHue/flutter_reactive_ble/blob/06f727777985403abc498cb5b246dbf137911119/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L62 

and then on an error or disconnect do a reconnect to the respective device

**Comment by skast96** [comment]
Thank you for your answer. I did find another approach by only using "connectToDevice" and waiting for "onDone" if the connection state of the device is disconnected, I close the current subscription and retry to start a new subscription to "connectToDevice", which is working quite well.
