### ISSUE TITLE
ConnectionTimeout is set. It doesn't seem to work  

### ISSUE THREAD

**Issue by jahnli** [PhilipsHue/flutter_reactive_ble#378]
![微信图片_20210926182735](https://user-images.githubusercontent.com/20943608/134804018-d77eb32b-d535-4cae-b5f3-29f7d98ce5ff.png)

When I set up a second overtime, it will not be disconnected or return an error, bluetooth status has also been a DeviceConnectionState. Connecting

**Comment by jahnli** [comment]
How do I catch mistakes, how to terminate DeviceConnectionState. Connecting

**Comment by remonh87** [comment]
we will terminate the stream when the device gets disconnected so you probably will not get the update. However you can use the https://github.com/PhilipsHue/flutter_reactive_ble/blob/876de0df13410a93a9034f39e65dce7833bd7126/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L62  in order to check if the device is disconnect or use `onDone` function in the stream.listen .

**Comment by jahnli** [comment]
> 当设备断开连接时，我们将终止流，因此您可能无法获得更新。但是，您可以使用
> 
> https://github.com/PhilipsHue/flutter_reactive_ble/blob/876de0df13410a93a9034f39e65dce7833bd7126/packages/flutter_reactive_ble/lib/src/reactive_ble.dart#L62
> 
> 为了检查设备是否断开连接或使用`onDone`stream.listen 中的功能。

I can get a DeviceConnectionState by checking the flow, but I can't disconnect the device from that state

**Comment by remonh87** [comment]
that is what I meant you can use the operation that I suggested and you will get a disconnected event. The way this library works is that we disconnect a device once the stream is cancelled.
