### ISSUE TITLE
Writing to multiple devices

### ISSUE THREAD

**Issue by santa010** [PhilipsHue/flutter_reactive_ble#614]
I am trying to send messages to multiple connected devices using `writeCharacteristicWithoutResponse` and I would expect a somewhat simultaneous change on the devices, but there seems to be a visible delay between execution on each device (enough that you can see a chain reaction from device 1 to device N). Does anyone know, if this is a limit of the library itself (i.e. the way it's designed or something similar)?

**Comment by paintingStyle** [comment]
> I am trying to send messages to multiple connected devices using `writeCharacteristicWithoutResponse` and I would expect a somewhat simultaneous change on the devices, but there seems to be a visible delay between execution on each device (enough that you can see a chain reaction from device 1 to device N). Does anyone know, if this is a limit of the library itself (i.e. the way it's designed or something similar)?

I also have this problem，did you solve it

I want to ask a question. Due to the company's business, there are 5 bluetooth devices. I need to connect 5 devices at the same time, and get the data and update data of the device at the same time. I checked the information on the Internet and found that Android needs to send data serially.

https://stackoverflow.com/questions/28016571/robustly-communicating-with-multiple-ble-devices-simultaneously-on-android

Is there a way to write and update the characteristics of multiple devices at the same time?

**Comment by Taym95** [comment]
I dont think Ble works like this, from doc `BluetoothGatt object you should only execute one operation at a time`.
