### ISSUE TITLE
OBD 2 BLE devices are not showing as part of ble scan results

### ISSUE THREAD

**Issue by rahul-yr** [PhilipsHue/flutter_reactive_ble#707]
OBD 2 ELM BLE devices are not showing as part of device scan list with below config.

   final flutterReactiveBle = FlutterReactiveBle();
    List<DiscoveredDevice> devices = [];

    final subscription = flutterReactiveBle.scanForDevices(
        withServices: [],
        scanMode: ScanMode.lowLatency,
        requireLocationServicesEnabled: false).listen((scanResult) {
      // do something with scan results
      final knownDeviceIndex = devices.indexWhere((d) => d.id == scanResult.id);
      if (knownDeviceIndex >= 0) {
        devices[knownDeviceIndex] = scanResult;
      } else {
        if (scanResult.name.isNotEmpty) {
          devices.add(scanResult);
        }
      }
    });

    //   add a timeout to stop scanning after a given time
    await Future.delayed(const Duration(seconds: 4));
    await subscription.cancel();
    log('devices : $devices', name: 'devices');
    return devices;

I could see other devices only OBD devices are not visible. And tested with other apps it's working fine

**Comment by remonh87** [comment]
I am going through some old issues. Sorry for not responding but I was working on other projects. I would double check if the device supports bluetooth and also check if you see the OBD device using a scanner like nerf connect.

Closing if for now since it is an old issue. Feel free to file another one and we make sure to react quicker,.
